#!/usr/bin/env python3
"""
config_manager.py - Manage email notification configuration

Commands:
    save --send <email> --auth <password> --recv <email>  Save configuration
    enable                                                 Enable notifications
    disable                                                Disable notifications
    status                                                 Show current status
    test                                                   Send test email
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from datetime import datetime

CONFIG_DIR = Path.home() / ".claude-notify"
CONFIG_FILE = CONFIG_DIR / "config.json"
HOOK_SCRIPT = CONFIG_DIR / "post-generate-hook.sh"


def load_config() -> dict:
    """Load configuration from file."""
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE, "r") as f:
            return json.load(f)
    return {
        "sender": "",
        "receiver": "",
        "enabled": False,
        "postfix_configured": False,
        "created_at": "",
        "updated_at": ""
    }


def save_config(config: dict) -> None:
    """Save configuration to file."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config["updated_at"] = datetime.now().isoformat()
    if not config.get("created_at"):
        config["created_at"] = config["updated_at"]
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)
    os.chmod(CONFIG_FILE, 0o600)


def setup_postfix(sender: str, auth: str) -> bool:
    """Run Postfix setup script."""
    script_dir = Path(__file__).parent
    setup_script = script_dir / "setup_postfix_gmail.sh"
    
    if not setup_script.exists():
        print(f"Error: Setup script not found: {setup_script}")
        return False
    
    try:
        result = subprocess.run(
            ["bash", str(setup_script), sender, auth],
            check=True,
            capture_output=True,
            text=True
        )
        print(result.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Postfix setup failed:\n{e.stderr}")
        return False


def create_hook_script(receiver: str) -> None:
    """Create the post-generation hook script."""
    script_dir = Path(__file__).parent
    send_script = script_dir / "send_notification.py"
    
    hook_content = f"""#!/bin/bash
# Claude Code Post-Generation Hook
# Auto-generated by email-notify

TASK_INFO="$1"
RECEIVER="{receiver}"

if command -v python3 &> /dev/null; then
    python3 "{send_script}" "$RECEIVER" "$TASK_INFO"
else
    echo "Claude Code task completed: $TASK_INFO" | mail -s "[Claude Code] Task Completed" "$RECEIVER"
fi
"""
    
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with open(HOOK_SCRIPT, "w") as f:
        f.write(hook_content)
    os.chmod(HOOK_SCRIPT, 0o755)
    print(f"Hook script created: {HOOK_SCRIPT}")


def send_test_email(receiver: str, subject: str = None, body: str = None) -> bool:
    """Send a test email."""
    if not subject:
        subject = "[Claude Code] Test Notification"
    if not body:
        body = f"Email notification test at {datetime.now().isoformat()}\n\nConfiguration successful."
    
    try:
        process = subprocess.Popen(
            ["mail", "-s", subject, receiver],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, stderr = process.communicate(input=body, timeout=30)
        
        if process.returncode == 0:
            print(f"✓ Test email sent to {receiver}")
            return True
        else:
            print(f"✗ Failed to send email: {stderr}")
            return False
    except subprocess.TimeoutExpired:
        process.kill()
        print("✗ Email send timeout")
        return False
    except FileNotFoundError:
        print("✗ 'mail' command not found. Ensure mailutils is installed.")
        return False


def cmd_save(args) -> int:
    """Save configuration command."""
    config = load_config()
    
    print("=== Setting up Gmail SMTP relay ===")
    if setup_postfix(args.send, args.auth):
        config["postfix_configured"] = True
    else:
        print("Warning: Postfix setup may have issues. Continue anyway.")
        config["postfix_configured"] = False
    
    config["sender"] = args.send
    config["receiver"] = args.recv
    config["enabled"] = True
    
    save_config(config)
    create_hook_script(args.recv)
    
    print("\n=== Configuration saved ===")
    print(f"Sender:   {args.send}")
    print(f"Receiver: {args.recv}")
    print(f"Config:   {CONFIG_FILE}")
    print(f"Hook:     {HOOK_SCRIPT}")
    
    print("\n=== Sending test email ===")
    send_test_email(args.recv)
    
    print("\n=== Integration ===")
    print("Add to your Claude Code hooks configuration:")
    print(f"  post_generation_hook: {HOOK_SCRIPT}")
    
    return 0


def cmd_enable(args) -> int:
    """Enable notifications."""
    config = load_config()
    
    if not config.get("receiver"):
        print("Error: No configuration found. Run 'notify-config' first.")
        return 1
    
    config["enabled"] = True
    save_config(config)
    create_hook_script(config["receiver"])
    
    print("✓ Email notifications enabled")
    print(f"  Receiver: {config['receiver']}")
    return 0


def cmd_disable(args) -> int:
    """Disable notifications."""
    config = load_config()
    config["enabled"] = False
    save_config(config)
    
    print("✓ Email notifications disabled")
    return 0


def cmd_status(args) -> int:
    """Show current status."""
    config = load_config()
    
    print("=== Email Notify Status ===")
    print(f"Enabled:           {config.get('enabled', False)}")
    print(f"Sender:            {config.get('sender', 'Not configured')}")
    print(f"Receiver:          {config.get('receiver', 'Not configured')}")
    print(f"Postfix configured:{config.get('postfix_configured', False)}")
    print(f"Config file:       {CONFIG_FILE}")
    print(f"Hook script:       {HOOK_SCRIPT}")
    print(f"Hook exists:       {HOOK_SCRIPT.exists()}")
    
    return 0


def cmd_test(args) -> int:
    """Send test email."""
    config = load_config()
    
    if not config.get("receiver"):
        print("Error: No receiver configured. Run 'notify-config' first.")
        return 1
    
    return 0 if send_test_email(config["receiver"]) else 1


def main():
    parser = argparse.ArgumentParser(
        description="Manage Claude Code email notifications"
    )
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # save command
    save_parser = subparsers.add_parser("save", help="Save configuration")
    save_parser.add_argument("--send", required=True, help="Sender Gmail address")
    save_parser.add_argument("--auth", required=True, help="Gmail App Password")
    save_parser.add_argument("--recv", required=True, help="Receiver email address")
    save_parser.set_defaults(func=cmd_save)
    
    # enable command
    enable_parser = subparsers.add_parser("enable", help="Enable notifications")
    enable_parser.set_defaults(func=cmd_enable)
    
    # disable command
    disable_parser = subparsers.add_parser("disable", help="Disable notifications")
    disable_parser.set_defaults(func=cmd_disable)
    
    # status command
    status_parser = subparsers.add_parser("status", help="Show status")
    status_parser.set_defaults(func=cmd_status)
    
    # test command
    test_parser = subparsers.add_parser("test", help="Send test email")
    test_parser.set_defaults(func=cmd_test)
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return 1
    
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
