from __future__ import annotations

from pathlib import Path

from .config import GUIDE_VERSION, IndexerConfig, PLUGIN_NAME
from .util import generated_artifact_path, write_text_if_changed


def build_generated_guides(
    *,
    config: IndexerConfig,
    root_metadata: dict,
    directory_metadata: list[dict],
    file_metadata: list[dict],
    provider,
) -> dict[str, str]:
    important_dirs = [item for item in directory_metadata if item["path"] != "."][:8]
    important_files = sorted(file_metadata, key=lambda item: (item.get("importance") != "high", item["path"]))[:8]
    generated_agents = provider.render_guide(
        root_metadata=root_metadata,
        important_dirs=important_dirs,
        important_files=important_files,
    )
    repo_map = _render_repo_map(directory_metadata, file_metadata)
    generated_claude = "\n".join(
        [
            "@AGENTS.md",
            "",
            "## Claude Code specifics",
            "- Prefer `.claude/rules/` for path-scoped rules.",
            "- Keep subdirectory `CLAUDE.md` usage minimal.",
            "- Use `.claude/skills/repo-index` or `.claude/skills/repo-read` when the task matches.",
            "",
        ]
    )
    return {
        "AGENTS.generated.md": generated_agents,
        "CLAUDE.generated.md": generated_claude,
        "repo-map.md": repo_map,
    }


def write_generated_guides(config: IndexerConfig, guides: dict[str, str]) -> list[str]:
    written: list[str] = []
    for name, content in guides.items():
        target = generated_artifact_path(config.generated_dir, name)
        if write_text_if_changed(target, content):
            written.append(str(target))
    return written


def export_host_guides(config: IndexerConfig, *, root_metadata: dict, directory_metadata: list[dict], file_metadata: list[dict]) -> list[str]:
    root_agents = _render_root_agents(root_metadata, directory_metadata)
    root_claude = "\n".join(
        [
            "@AGENTS.md",
            "",
            "## Claude Code specifics",
            "- Prefer `.claude/rules/` for path-scoped rules.",
            "- Keep subdirectory `CLAUDE.md` usage minimal.",
            "- Use project skills under `.claude/skills` when the task matches.",
            "",
        ]
    )
    reading_policy = _render_reading_policy()
    indexing_policy = _render_indexing_policy(config)
    verification_policy = _render_verification_policy(config)
    repo_index_skill, repo_index_reference = _render_repo_index_skill(config)
    repo_read_skill, repo_read_reference = _render_repo_read_skill(config)

    writes = [
        (config.root / "AGENTS.md", root_agents),
        (config.root / "CLAUDE.md", root_claude),
        (config.root / ".claude" / "rules" / "reading-policy.md", reading_policy),
        (config.root / ".claude" / "rules" / "indexing-policy.md", indexing_policy),
        (config.root / ".claude" / "rules" / "verification-policy.md", verification_policy),
        (config.root / ".agents" / "skills" / "repo-index" / "SKILL.md", repo_index_skill),
        (config.root / ".agents" / "skills" / "repo-index" / "reference.md", repo_index_reference),
        (config.root / ".agents" / "skills" / "repo-read" / "SKILL.md", repo_read_skill),
        (config.root / ".agents" / "skills" / "repo-read" / "reference.md", repo_read_reference),
        (config.root / ".claude" / "skills" / "repo-index" / "SKILL.md", repo_index_skill),
        (config.root / ".claude" / "skills" / "repo-index" / "reference.md", repo_index_reference),
        (config.root / ".claude" / "skills" / "repo-read" / "SKILL.md", repo_read_skill),
        (config.root / ".claude" / "skills" / "repo-read" / "reference.md", repo_read_reference),
    ]

    written: list[str] = []
    for path, content in writes:
        if write_text_if_changed(path, content):
            written.append(str(path))
    return written


def _render_root_agents(root_metadata: dict, directory_metadata: list[dict]) -> str:
    lines = [
        "# Repository Guide",
        "",
        f"Generated by `{PLUGIN_NAME}` guide pipeline `{GUIDE_VERSION}`.",
        "",
        "## Purpose",
        "",
        root_metadata.get("role", "Repository index entrypoint."),
        "",
        "## Repository Map",
        "",
    ]
    interesting = [item for item in directory_metadata if item["path"] != "."][:8]
    if interesting:
        for item in interesting:
            lines.append(f"- `{item['path']}`: {item.get('role', 'directory')}")
    else:
        lines.append("- Read `.scanmeta/dirs/root.json` after the first refresh.")
    lines.extend(
        [
            "",
            "## Progressive Reading Policy",
            "",
            "1. Read this file, then `CLAUDE.md` when using Claude Code.",
            "2. Read `.scanmeta/dirs/root.json` and the nearest directory summaries.",
            "3. Read `.scanmeta/files/*.json` before file bodies.",
            "4. Read `.scanmeta/sections/*.json` for large files before opening full source.",
            "5. Escalate to full-file reads only for patching, exact behavior, unresolved ambiguity, or line-level reasoning.",
            "",
            "## Verification",
            "",
            "- Refresh the index after structural changes.",
            "- Run `python3 tools/repo_indexer.py refresh --root .` when metadata is stale.",
            "- Run `python3 tools/repo_indexer.py doctor --root .` before trusting damaged artifacts.",
            "",
            "## Guardrails",
            "",
            "- Do not edit `.scanmeta/state/index.sqlite` manually.",
            "- Treat `.scanmeta/files`, `.scanmeta/sections`, and `.scanmeta/dirs` as generated sidecars.",
            "- Keep root guides short; detailed maps belong under `.scanmeta/generated/`.",
            "",
        ]
    )
    return "\n".join(lines)


def _render_repo_map(directory_metadata: list[dict], file_metadata: list[dict]) -> str:
    lines = ["# Repository Map", ""]
    for item in directory_metadata:
        if item["path"] == ".":
            continue
        lines.append(f"## {item['path']}")
        lines.append("")
        lines.append(f"- Role: {item.get('role', 'directory')}")
        if item.get("topics"):
            lines.append(f"- Topics: {', '.join(item['topics'])}")
        if item.get("read_order"):
            lines.append(f"- Read order: {', '.join(item['read_order'])}")
        lines.append("")
    lines.append("## High-Signal Files")
    lines.append("")
    for item in file_metadata[:12]:
        lines.append(f"- `{item['path']}`: {item.get('summary', '')}")
    lines.append("")
    return "\n".join(lines)


def _render_reading_policy() -> str:
    return "\n".join(
        [
            "# Reading Policy",
            "",
            "Default read order:",
            "",
            "1. `AGENTS.md` / `CLAUDE.md`",
            "2. `.scanmeta/dirs/root.json` and nearest directory summaries",
            "3. `.scanmeta/files/*.json` sidecars",
            "4. `.scanmeta/sections/*.json` for large files",
            "5. Relevant file sections",
            "6. Full file bodies only when exact behavior, patching, or ambiguity requires it",
            "",
        ]
    )


def _render_indexing_policy(config: IndexerConfig) -> str:
    return "\n".join(
        [
            "# Indexing Policy",
            "",
            "- Runtime state lives in `.scanmeta/state/index.sqlite`.",
            "- File metadata sidecars live in `.scanmeta/files/`.",
            "- Section indexes live in `.scanmeta/sections/` for large files.",
            "- Directory summaries live in `.scanmeta/dirs/`.",
            "- Generated guides live in `.scanmeta/generated/` and export into root guides and host skills.",
            f"- Markdown inline frontmatter is {'enabled' if config.inline_markdown_frontmatter else 'disabled'} by default for this repository.",
            "",
        ]
    )


def _render_verification_policy(config: IndexerConfig) -> str:
    return "\n".join(
        [
            "# Verification Policy",
            "",
            f"- Primary refresh command: `python3 tools/repo_indexer.py refresh --root {config.root}`",
            f"- Validate artifacts with `python3 tools/repo_indexer.py doctor --root {config.root}`",
            "- Re-export guides after schema or directory role changes.",
            "- Treat broken or missing sidecars as a reason to refresh before editing by summary alone.",
            "",
        ]
    )


def _render_repo_index_skill(config: IndexerConfig) -> tuple[str, str]:
    skill = "\n".join(
        [
            "---",
            "name: repo-index",
            "description: Refresh the repository knowledge layer under .scanmeta and export host guides when the index is stale or missing.",
            "---",
            "",
            "# Repo Index",
            "",
            "Use this skill when the repository needs a fresh or incremental index.",
            "",
            "## Workflow",
            "",
            "1. Run the refresh command from the repository root.",
            "2. Inspect `.scanmeta/runs/*.json` and `.scanmeta/generated/repo-map.md`.",
            "3. Run `doctor` if any artifact looks stale or malformed.",
            "4. Re-run `export-guides` after schema changes or manual artifact repair.",
            "",
            "See `reference.md` for commands and output layout.",
            "",
        ]
    )
    reference = "\n".join(
        [
            "# Repo Index Reference",
            "",
            f"- Refresh: `python3 tools/repo_indexer.py refresh --root {config.root}`",
            f"- Preview diff: `python3 tools/repo_indexer.py scan --root {config.root}`",
            f"- Partial refresh: `python3 tools/repo_indexer.py refresh --root {config.root} --path src/`",
            f"- Validate: `python3 tools/repo_indexer.py doctor --root {config.root}`",
            "",
        ]
    )
    return skill, reference


def _render_repo_read_skill(config: IndexerConfig) -> tuple[str, str]:
    skill = "\n".join(
        [
            "---",
            "name: repo-read",
            "description: Follow the deterministic read planner so agent work starts with summaries and escalates only when necessary.",
            "---",
            "",
            "# Repo Read",
            "",
            "Use this skill when you need to inspect the repository without opening large file bodies blindly.",
            "",
            "## Workflow",
            "",
            "1. Read `AGENTS.md` and the nearest `.claude/rules/` guidance.",
            "2. Read `.scanmeta/dirs/root.json` and the nearest directory metadata.",
            "3. Read `.scanmeta/files/*.json` for candidate files.",
            "4. Read `.scanmeta/sections/*.json` for large files.",
            "5. Escalate to full-file reads only for patching or exact behavior validation.",
            "",
            "See `reference.md` for the escalation triggers.",
            "",
        ]
    )
    reference = "\n".join(
        [
            "# Repo Read Reference",
            "",
            "- Full-file reads are reserved for patching, line-level reasoning, exact behavior checks, or unresolved ambiguity.",
            "- Large files should be approached through `.scanmeta/sections/*.json` first.",
            "- If metadata is missing or stale, refresh the index before relying on the summaries.",
            "",
        ]
    )
    return skill, reference
